<?php

return [
    [
        'id' => 1,
        'name' => '腕時計',
        'price' => 15000,
        'description' => 'スタイリッシュなデザインのメンズ腕時計',
        'img_url' => '/storage/時計.jpg',
        'condition' => '良好',
        'categories' => ['メンズ', 'アクセサリー'],
    ],
    [
        'id' => 2,
        'name' => 'HDD',
        'price' => 5000,
        'description' => '高速で信頼性の高いハードディスク',
        'img_url' => '/storage/HDD.jpg',
        'condition' => '目立った傷や汚れなし',
        'categories' => ['家電'],
    ],
    [
        'id' => 3,
        'name' => '玉ねぎ3束',
        'price' => 300,
        'description' => '新鮮な玉ねぎ3束のセット',
        'img_url' => '/storage/玉ねぎ３束.jpg',
        'condition' => 'やや傷や汚れあり',
        'categories' => ['キッチン'],
    ],
    [
        'id' => 4,
        'name' => '革靴',
        'price' => 4000,
        'description' => 'クラシックなデザインの革靴',
        'img_url' => '/storage/革靴.jpg',
        'condition' => '状態が悪い',
        'categories' => ['ファッション', 'メンズ'],
    ],
    [
        'id' => 5,
        'name' => 'ノートPC',
        'price' => 45000,
        'description' => '高性能なノートパソコン',
        'img_url' => '/storage/ノートPC.jpg',
        'condition' => '良好',
        'categories' => ['家電'],
    ],
    [
        'id' => 6,
        'name' => 'マイク',
        'price' => 8000,
        'description' => '高音質のレコーディング用マイク',
        'img_url' => '/storage/マイク.jpg',
        'condition' => '目立った傷や汚れなし',
        'categories' => ['家電', 'おもちゃ'],
    ],
    [
        'id' => 7,
        'name' => 'ショルダーバッグ',
        'price' => 3500,
        'description' => 'おしゃれなショルダーバッグ',
        'img_url' => '/storage/ショルダーバッグ.jpg',
        'condition' => 'やや傷や汚れあり',
        'categories' => ['レディース', 'ハンドメイド'],
    ],
    [
        'id' => 8,
        'name' => 'タンブラー',
        'price' => 500,
        'description' => '使いやすいタンブラー',
        'img_url' => '/storage/タンブラー.jpg',
        'condition' => '状態が悪い',
        'categories' => ['スポーツ'],
    ],
    [
        'id' => 9,
        'name' => 'コーヒーミル',
        'price' => 4000,
        'description' => '手動のコーヒーミル',
        'img_url' => '/storage/コーヒーミル.jpg',
        'condition' => '良好',
        'categories' => ['キッチン'],
    ],
    [
        'id' => 10,
        'name' => 'メイクセット',
        'price' => 2500,
        'description' => '便利なメイクアップセット',
        'img_url' => '/storage/メイクセット.jpg',
        'condition' => '目立った傷や汚れなし',
        'categories' => ['レディース', 'コスメ'],
    ],
];
